apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: front-app
  template:
    metadata:
      labels: front-app
    spec:
      containers:
        - name: front
          image: {{ .Values.frontendImage }}
          ports:
            - containerPort: {{ .Values.frontendContainerPort }}